spring.application.name=Stickers
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
logging.level.root=${LOG_LEVEL:INFO}
logging.file.name=${LOG_FILE_NAME:/Users/syoges/Documents/app.log}
logging.pattern.file={"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","logger":"%c","message":"%m"}
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
#to store the data in file to prevent the rollback in h2 database
spring.datasource.url=jdbc:h2:file:~/eazystore;AUTO_SERVER=true
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.sql.init.mode=always
#written optional because if not present then it will not throw any runtime exception and will the run the application
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/eazystore/actuator
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.exclude=beans,health
#spring.security.user.name=${EAZYSTORE_USERNAME:yogesh}
#spring.security.user.password=${EAZYSTORE_PASSWORD:stickers}
#spring.security.user.roles=${EAZYSTORE_ROLES:USER,ADMIN}

stripe.apiKey=${STRIPE_API_KEY:}


